name: Django Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python 3.11.5
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.5

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Apply Migrations
        run: python3 manage.py migrate

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . || echo "Lint warnings ignored"

      - name: Run Django Tests
        run: |
          python3 manage.py test || exit 1
